import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";

vi.mock("node:fs/promises", () => ({
  readFile: vi.fn().mockRejectedValue(new Error("ENOENT")),
  writeFile: vi.fn().mockResolvedValue(undefined),
  mkdir: vi.fn().mockResolvedValue(undefined),
  readdir: vi.fn().mockResolvedValue([]),
  access: vi.fn().mockRejectedValue(new Error("ENOENT")),
}));

vi.spyOn(process, "exit").mockImplementation((() => {}) as never);

const HEAD_SCAFFOLD = `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Investment Reports</title>
  <style>
    body { background: #0f0f1a; }
    .accent { color: #3b82f6; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Investment Agent Reports</h1>
    <!-- REPORT_ENTRIES -->
    <ul class="report-list">
      <li class="report-item">
        <div class="report-date">2026-07-01</div>
        <div class="report-links">
          <a href="2026-07-01/daily-report.html">Daily Report</a>
          <a href="2026-07-01/meeting-minutes.html">Meeting Minutes</a>
          <a href="2026-07-01/portfolio-report.html">Portfolio Report</a>
        </div>
      </li>
      <li class="report-item">
        <div class="report-date">2026-06-10</div>
        <div class="report-links">
          <a href="2026-06-10/daily-report.html">Daily Report</a>
          <a href="2026-06-10/meeting-minutes.html">Meeting Minutes</a>
        </div>
      </li>
    </ul>
    <!-- /REPORT_ENTRIES -->
    <div class="footer">Generated by Investment Agent System</div>
  </div>
</body>
</html>`;

const HEAD_SCAFFOLD_WITH_STALE_LINK = `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Investment Reports</title>
  <style>
    body { background: #0f0f1a; }
    .accent { color: #3b82f6; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Investment Agent Reports</h1>
    <!-- REPORT_ENTRIES -->
    <ul class="report-list">
      <li class="report-item">
        <div class="report-date">2026-07-01</div>
        <div class="report-links">
          <a href="2026-07-01/daily-report.html">Daily Report</a>
          <a href="2026-07-01/meeting-minutes.html">Meeting Minutes</a>
          <a href="2026-07-01/portfolio-report.html">Portfolio Report</a>
          <a href="2026-07-01/news-digest.html">News Digest</a>
        </div>
      </li>
      <li class="report-item">
        <div class="report-date">2026-06-10</div>
        <div class="report-links">
          <a href="2026-06-10/daily-report.html">Daily Report</a>
          <a href="2026-06-10/meeting-minutes.html">Meeting Minutes</a>
        </div>
      </li>
    </ul>
    <!-- /REPORT_ENTRIES -->
    <div class="footer">Generated by Investment Agent System</div>
  </div>
</body>
</html>`;

const NEW_DATE = "2026-07-02";

describe("update-index.ts", () => {
  beforeEach(async () => {
    const fsMock = await import("node:fs/promises");
    (fsMock.writeFile as ReturnType<typeof vi.fn>).mockClear();
    (fsMock.readFile as ReturnType<typeof vi.fn>).mockReset();
    (fsMock.readFile as ReturnType<typeof vi.fn>).mockImplementation((path: string) => {
      if (String(path).includes("index.html")) {
        return Promise.resolve(HEAD_SCAFFOLD);
      }
      return Promise.reject(new Error("ENOENT"));
    });
    (fsMock.access as ReturnType<typeof vi.fn>).mockReset();
    (fsMock.access as ReturnType<typeof vi.fn>).mockRejectedValue(new Error("ENOENT"));
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("groups entries by month with exactly one details block per month, newest month open", async () => {
    const fsMock = await import("node:fs/promises");
    const { updateIndexHtml } = await import("./update-index.js");

    await updateIndexHtml(NEW_DATE);

    const writeCalls = (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls;
    const indexCall = writeCalls.find((call) => String(call[0]).includes("index.html"));
    expect(indexCall).toBeDefined();
    const output = String(indexCall![1]);

    const detailsMatches = output.match(/<details class="month-group"/g) ?? [];
    expect(detailsMatches.length).toBe(2);

    const julyBlockMatch = output.match(
      /<details class="month-group"( open)?>\s*<summary>2026年7月/,
    );
    expect(julyBlockMatch).toBeTruthy();
    expect(julyBlockMatch![1]).toBe(" open");

    const juneBlockMatch = output.match(
      /<details class="month-group"( open)?>\s*<summary>2026年6月/,
    );
    expect(juneBlockMatch).toBeTruthy();
    expect(juneBlockMatch![1]).toBeUndefined();
  });

  it("preserves the 2-link entry's exact hrefs without fabricating a 3rd link", async () => {
    const fsMock = await import("node:fs/promises");
    const { updateIndexHtml } = await import("./update-index.js");

    await updateIndexHtml(NEW_DATE);

    const writeCalls = (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls;
    const indexCall = writeCalls.find((call) => String(call[0]).includes("index.html"));
    const output = String(indexCall![1]);

    const juneEntryMatch = output.match(
      /<div class="report-date">2026-06-10<\/div>\s*<div class="report-links">([\s\S]*?)<\/div>/,
    );
    expect(juneEntryMatch).toBeTruthy();
    const juneLinksHtml = juneEntryMatch![1];
    expect(juneLinksHtml).toContain("2026-06-10/daily-report.html");
    expect(juneLinksHtml).toContain("2026-06-10/meeting-minutes.html");
    expect(juneLinksHtml).not.toContain("portfolio-report.html");
  });

  it("renders the newest entry as a hero block containing the latest date", async () => {
    const fsMock = await import("node:fs/promises");
    const { updateIndexHtml } = await import("./update-index.js");

    await updateIndexHtml(NEW_DATE);

    const writeCalls = (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls;
    const indexCall = writeCalls.find((call) => String(call[0]).includes("index.html"));
    const output = String(indexCall![1]);

    const heroMatch = output.match(/<div class="hero">[\s\S]*?<\/div>\s*<\/div>/);
    expect(heroMatch).toBeTruthy();
    expect(heroMatch![0]).toContain(NEW_DATE);
  });

  it("produces byte-identical output across two invocations on identical input (determinism)", async () => {
    const fsMock = await import("node:fs/promises");
    const { updateIndexHtml } = await import("./update-index.js");

    await updateIndexHtml(NEW_DATE);
    const firstOutput = String(
      (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls.find((call) =>
        String(call[0]).includes("index.html"),
      )![1],
    );

    (fsMock.writeFile as ReturnType<typeof vi.fn>).mockClear();

    await updateIndexHtml(NEW_DATE);
    const secondOutput = String(
      (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls.find((call) =>
        String(call[0]).includes("index.html"),
      )![1],
    );

    expect(secondOutput).toBe(firstOutput);
  });

  it("leaves content outside the REPORT_ENTRIES region unchanged", async () => {
    const fsMock = await import("node:fs/promises");
    const { updateIndexHtml } = await import("./update-index.js");

    await updateIndexHtml(NEW_DATE);

    const writeCalls = (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls;
    const indexCall = writeCalls.find((call) => String(call[0]).includes("index.html"));
    const output = String(indexCall![1]);

    expect(output).toContain("<title>Investment Reports</title>");
    expect(output).toContain("body { background: #0f0f1a; }");
    expect(output).toContain(".accent { color: #3b82f6; }");
    expect(output).toContain('<div class="footer">Generated by Investment Agent System</div>');
  });

  it("adds News Digest link", async () => {
    const fsMock = await import("node:fs/promises");
    (fsMock.access as ReturnType<typeof vi.fn>).mockImplementation((path: string) => {
      if (String(path).includes(`${NEW_DATE}/news-digest.html`)) return Promise.resolve(undefined);
      return Promise.reject(new Error("ENOENT"));
    });
    const { updateIndexHtml } = await import("./update-index.js");

    await updateIndexHtml(NEW_DATE);

    const writeCalls = (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls;
    const indexCall = writeCalls.find((call) => String(call[0]).includes("index.html"));
    const output = String(indexCall![1]);

    const newEntryMatch = output.match(
      new RegExp(
        `<div class="report-date">${NEW_DATE}</div>\\s*<div class="report-links">([\\s\\S]*?)</div>`,
      ),
    );
    expect(newEntryMatch).toBeTruthy();
    const linksHtml = newEntryMatch![1];
    expect(linksHtml).toContain(`<a href="${NEW_DATE}/news-digest.html">News Digest</a>`);

    const hrefOrder = [...linksHtml.matchAll(/<a href="([^"]*)">/g)].map((m) => m[1]);
    expect(hrefOrder[hrefOrder.length - 1]).toBe(`${NEW_DATE}/news-digest.html`);
  });

  it("omits News Digest link", async () => {
    const fsMock = await import("node:fs/promises");
    // access rejects for all paths by default (set in beforeEach) — file does not exist
    const { updateIndexHtml } = await import("./update-index.js");

    await updateIndexHtml(NEW_DATE);

    const writeCalls = (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls;
    const indexCall = writeCalls.find((call) => String(call[0]).includes("index.html"));
    const output = String(indexCall![1]);

    const juneEntryMatch = output.match(
      /<div class="report-date">2026-06-10<\/div>\s*<div class="report-links">([\s\S]*?)<\/div>/,
    );
    expect(juneEntryMatch).toBeTruthy();
    const juneLinksHtml = juneEntryMatch![1];
    expect(juneLinksHtml).not.toContain("news-digest.html");
    expect(juneLinksHtml).not.toContain("News Digest");
  });

  it("removes stale News Digest link", async () => {
    const fsMock = await import("node:fs/promises");
    (fsMock.readFile as ReturnType<typeof vi.fn>).mockImplementation((path: string) => {
      if (String(path).includes("index.html")) {
        return Promise.resolve(HEAD_SCAFFOLD_WITH_STALE_LINK);
      }
      return Promise.reject(new Error("ENOENT"));
    });
    // access rejects for all paths (default from beforeEach) — 2026-07-01/news-digest.html no longer exists
    const { updateIndexHtml } = await import("./update-index.js");

    await updateIndexHtml(NEW_DATE);

    const writeCalls = (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls;
    const indexCall = writeCalls.find((call) => String(call[0]).includes("index.html"));
    const output = String(indexCall![1]);

    const julyEntryMatch = output.match(
      /<div class="report-date">2026-07-01<\/div>\s*<div class="report-links">([\s\S]*?)<\/div>/,
    );
    expect(julyEntryMatch).toBeTruthy();
    const julyLinksHtml = julyEntryMatch![1];
    expect(julyLinksHtml).not.toContain("news-digest.html");
    expect(julyLinksHtml).not.toContain("News Digest");
  });

  it("preserves 3 links alongside News Digest", async () => {
    const fsMock = await import("node:fs/promises");
    (fsMock.access as ReturnType<typeof vi.fn>).mockImplementation((path: string) => {
      if (String(path).includes(`${NEW_DATE}/news-digest.html`)) return Promise.resolve(undefined);
      return Promise.reject(new Error("ENOENT"));
    });
    const { updateIndexHtml } = await import("./update-index.js");

    await updateIndexHtml(NEW_DATE);

    const writeCalls = (fsMock.writeFile as ReturnType<typeof vi.fn>).mock.calls;
    const indexCall = writeCalls.find((call) => String(call[0]).includes("index.html"));
    const output = String(indexCall![1]);

    const newEntryMatch = output.match(
      new RegExp(
        `<div class="report-date">${NEW_DATE}</div>\\s*<div class="report-links">([\\s\\S]*?)</div>`,
      ),
    );
    expect(newEntryMatch).toBeTruthy();
    const linksHtml = newEntryMatch![1];
    expect(linksHtml).toContain(`${NEW_DATE}/daily-report.html`);
    expect(linksHtml).toContain(`${NEW_DATE}/meeting-minutes.html`);
    expect(linksHtml).toContain(`${NEW_DATE}/portfolio-report.html`);
    expect(linksHtml).toContain(`${NEW_DATE}/news-digest.html`);
  });
});
